[package]
name = "prikey2keystore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eth-keystore = "0.5.0"
rand = "0.8.5"
anyhow = "1.0.68"
structopt = "0.3.26"